# ==================================
# DATOS GENERALES
# ==================================
spring.application.name=api-transacciones

server.port=8080


# ==================================
# JSON
# ==================================
spring.jackson.serialization.indent-output=true


# ==================================
# BASE DE DATOS H2 PERSISTENTE
# ==================================
spring.datasource.url=jdbc:h2:file:./data/transaccionesdb

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=


# ==================================
# JPA / HIBERNATE
# ==================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mantiene las tablas y actualiza cambios de Entity
spring.jpa.hibernate.ddl-auto=update


# Mostrar SQL generado
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# ==================================
# CONSOLA H2
# ==================================
spring.h2.console.enabled=true

spring.h2.console.path=/h2-console


# ==================================
# OPENFEIGN
# ==================================
logging.level.org.springframework.cloud.openfeign=DEBUG